### ISSUE TITLE
Conda installs version 0.3 -- Get no package pyvisa_sim found.

### ISSUE THREAD

**Issue by nate-h** [conda-forge/pyvisa-py-feedstock#22]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

Adding an issue here as suggested from [this issue](https://github.com/pyvisa/pyvisa-sim/issues/62).

 There's a bug when using the latest conda version of pyvisa-sim that gets resolved if I pip install the latest version.

### Installed packages

```shell
pyvisa                    1.12.0          py310h2ec42d9_0    https://artifactory.hrl.com/artifactory/api/conda/conda-forge
pyvisa-py                 0.5.3              pyh6c4a22f_0    https://artifactory.hrl.com/artifactory/api/conda/conda-forge
pyvisa-sim                0.3                        py_0    https://artifactory.hrl.com/artifactory/api/conda/conda-from-pypi
```

### Environment info

```shell
conda version : 4.11.0
    conda-build version : 3.20.5
         python version : 3.7.8.final.0
       virtual packages : __osx=10.15.7=0
                          __unix=0=0
                          __archspec=1=x86_64
             user-agent : conda/4.11.0 requests/2.26.0 CPython/3.7.8 Darwin/19.6.0 OSX/10.15.7
```

**Comment by mtsolmn** [comment]
@nate-h `pyvisa-sim` has been added onto `conda-forge`: https://github.com/conda-forge/staged-recipes/pull/21162. Don't expect it to be maintained - I am not a maintainer for pyvisa, only the Conda feedstock. Additionally, adding this issue here was not the correct place to address your concern, the other issue you made here was correct: https://github.com/pyvisa/pyvisa-sim/issues/62
